name: Build-package
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest,windows-latest,ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "SetUp java"
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          distribution: 'graalvm'
          java-version: 17
          native-image-job-reports: 'false'
      - name: 'SetUp Gradle'
        uses: gradle/gradle-build-action@v2.8.0
      - name: 'build'
        run: ./gradlew build
      - name: 'Upload build target'
        uses: actions/upload-artifact@v3
        with:
          name: telegram-stickers-bot-${{ runner.os }}-${{ github.sha }}
          path: |
            ./build/distributions/*.zip
          retention-days: 5